# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 20:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSubMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='Order | Orden', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('image', models.ImageField(default=None, help_text='Image | Imagen', upload_to='images/menus/')),
                ('active', models.BooleanField(default=True, help_text='Active | Activo')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Menu Sub Menus',
                'db_table': 'menu_submenus',
                'verbose_name': 'Menu Sub Menu',
                'ordering': ['order', 'menu', 'submenu'],
            },
        ),
    ]
