# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submenus', '0001_initial'),
        ('menus', '0001_initial'),
        ('menu_submenus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menusubmenu',
            name='menu',
            field=models.ForeignKey(help_text='Menu | Menús', on_delete=django.db.models.deletion.CASCADE, to='menus.Menu'),
        ),
        migrations.AddField(
            model_name='menusubmenu',
            name='submenu',
            field=models.ForeignKey(help_text='Sub Menu | Sub Menú', on_delete=django.db.models.deletion.CASCADE, to='submenus.SubMenu'),
        ),
    ]
