# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_submenus', '0002_auto_20180611_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusubmenu',
            name='image',
            field=models.ImageField(default=None, help_text='Image | Imagen', upload_to='images/menu-submenus/'),
        ),
    ]
