# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 20:29
from __future__ import unicode_literals

from django.db import migrations
import url_or_relative_url_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('submenus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='url',
            field=url_or_relative_url_field.fields.URLOrRelativeURLField(db_index=True, help_text='U.R.L. | U.R.L.', max_length=255),
        ),
    ]
