# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 23:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area_types', '0001_initial'),
        ('headquarterses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name | Nombre', max_length=100, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('initials', models.CharField(db_index=True, help_text='Initials | Iniciales', max_length=20, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(20)])),
                ('nominal_organic_structure_type', models.CharField(choices=[('No Asigando', 'No Asigando'), ('Alta Dirección', 'Alta Dirección'), ('Dirección', 'Dirección'), ('Consultoría', 'Consultoría'), ('Consejo', 'Consejo'), ('Control', 'Control'), ('Línea', 'Línea'), ('Descentralizado', 'Descentralizado')], help_text='Nominal organic structure Type | Tipo estructura orgánica nominal', max_length=15)),
                ('telephone_annex', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Telephone annex | Anexo telefónica', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('fax', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Fax | Fax', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('logo', models.ImageField(blank=True, default='images/defaults/Default-1.png', help_text='Logo | logo', null=True, upload_to='images/areas/')),
                ('active', models.BooleanField(default=True, help_text='Active | Activo')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('area_type', models.ForeignKey(help_text='AreaType | Tipo área', on_delete=django.db.models.deletion.CASCADE, to='area_types.AreaType')),
                ('dependency', models.ForeignKey(blank=True, help_text='Dependency | Dependencia', null=True, on_delete=django.db.models.deletion.CASCADE, to='areas.Area')),
                ('headquarters', models.ForeignKey(help_text='Headquarters | Sede', on_delete=django.db.models.deletion.CASCADE, to='headquarterses.Headquarters')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'db_table': 'areas',
                'ordering': ['headquarters', 'name', 'initials'],
            },
        ),
    ]
