# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['headquarters', 'area_type', 'name', 'initials'], 'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
    ]
