# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='nominal_organic_structure_type',
            field=models.CharField(choices=[('No Asigando', 'No Asigando'), ('Alta Dirección', 'Alta Dirección'), ('Dirección', 'Dirección'), ('Consultoría', 'Consultoría'), ('Consejo', 'Consejo'), ('Control', 'Control'), ('Línea', 'Línea'), ('Descentralizado', 'Descentralizado')], default='No asignado', help_text='Gender | Género', max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='area',
            name='headquarters',
            field=models.ForeignKey(help_text='Nominal organic structure type | Tipo estructura orgánica nominal', on_delete=django.db.models.deletion.CASCADE, to='headquarterses.Headquarters'),
        ),
    ]
