# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_auto_20180622_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='headquarters',
            field=models.ForeignKey(help_text='Headquarters | Sede', on_delete=django.db.models.deletion.CASCADE, to='headquarterses.Headquarters'),
        ),
        migrations.AlterField(
            model_name='area',
            name='nominal_organic_structure_type',
            field=models.CharField(choices=[('No Asigando', 'No Asigando'), ('Alta Dirección', 'Alta Dirección'), ('Dirección', 'Dirección'), ('Consultoría', 'Consultoría'), ('Consejo', 'Consejo'), ('Control', 'Control'), ('Línea', 'Línea'), ('Descentralizado', 'Descentralizado')], help_text='Nominal organic structure Type | Tipo estructura orgánica nominal', max_length=15),
        ),
    ]
