# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0003_auto_20180622_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='dependency',
            field=models.ForeignKey(blank=True, help_text='Dependency | Dependencia', null=True, on_delete=django.db.models.deletion.CASCADE, to='areas.Area'),
        ),
    ]
