# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 16:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0005_auto_20180623_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='initials',
            field=models.CharField(db_index=True, help_text='Initials | Iniciales', max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(20)]),
        ),
    ]
