# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_remove_module_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='image',
            field=models.ImageField(default='images/defaults/Default-1.png', help_text='Image | Imagen', upload_to='images/modules/'),
        ),
    ]
