# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 17:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identification_document_types', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificationDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, help_text='Number | Número', max_length=25, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(25)])),
                ('idenfication_document', models.ForeignKey(help_text='Identification document | Documento de identificación', on_delete=django.db.models.deletion.CASCADE, to='identification_document_types.IdentificationDocumentType')),
                ('person', models.ForeignKey(help_text='Person | Persona', on_delete=django.db.models.deletion.CASCADE, to='persons.Person')),
            ],
            options={
                'verbose_name': 'Identification Document',
                'verbose_name_plural': 'Identification Documents',
                'db_table': 'identification_documents',
                'ordering': ['number'],
            },
        ),
    ]
