# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identification_document_types', '0002_auto_20180625_1204'),
        ('identification_documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identificationdocument',
            name='idenfication_document',
        ),
        migrations.AddField(
            model_name='identificationdocument',
            name='identification_document_type',
            field=models.ForeignKey(default='', help_text='Identification document type | Tipo Documento de identificación', on_delete=django.db.models.deletion.CASCADE, to='identification_document_types.IdentificationDocumentType'),
            preserve_default=False,
        ),
    ]
