# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='person',
            field=models.OneToOneField(help_text='Auth user profile | Perfil de usuario', on_delete=django.db.models.deletion.CASCADE, to='persons.Person'),
        ),
    ]
