# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='person',
            field=models.OneToOneField(help_text='Person | Persona', on_delete=django.db.models.deletion.CASCADE, to='persons.Person'),
        ),
    ]
