# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 01:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificationDocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_document_class', models.CharField(choices=[('Documento Identidad', 'Documento Identidad'), ('Identificación Tributaria', 'Identificación Tributaria')], help_text='Identification document type | Tipo documento de identificación', max_length=25)),
                ('name', models.CharField(db_index=True, help_text='Name | Nombre', max_length=100, unique=True)),
                ('initials', models.CharField(db_index=True, help_text='Initials | Iniciales', max_length=20, unique=True)),
                ('digits', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Digits | Dígitos', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Identification Document Type',
                'verbose_name_plural': 'Identification Document Types',
                'db_table': 'identification_document_types',
                'ordering': ['identification_document_class', 'name', 'initials', 'digits'],
            },
        ),
    ]
