# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 17:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identification_document_types', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificationdocumenttype',
            name='digits',
            field=models.PositiveSmallIntegerField(default=0, help_text='Digits | Dígitos', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
