# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 23:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_scope', models.CharField(choices=[('Actividad Econónica', 'Actividad Econónica'), ('Ámbito de Operación', 'Ámbito de Operación'), ('Composición del Capital', 'Composición del Capital'), ('Forma Jurídica', 'Forma Jurídica'), ('Tamaño', 'Tamaño')], db_index=True, help_text='Entity Scope | Ámbito Entidad', max_length=50)),
                ('name', models.CharField(db_index=True, help_text='Name | Nombre', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Entity Class',
                'verbose_name_plural': 'Entity Classes',
                'db_table': 'entity_classes',
                'ordering': ['entity_scope', 'name'],
            },
        ),
    ]
