# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 21:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='Order | Orden', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('image', models.ImageField(default=None, help_text='Image | Imagen', upload_to='images/module-menus/')),
                ('active', models.BooleanField(default=True, help_text='Active | Activo')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('menu', models.ForeignKey(help_text='Menu | Menús', on_delete=django.db.models.deletion.CASCADE, to='menus.Menu')),
            ],
            options={
                'verbose_name': 'Module Menu',
                'db_table': 'module_menus',
                'verbose_name_plural': 'Module Menus',
                'ordering': ['order', 'module', 'menu'],
            },
        ),
    ]
