# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
        ('module_menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulemenu',
            name='module',
            field=models.ForeignKey(help_text='Module | Módule', on_delete=django.db.models.deletion.CASCADE, to='modules.Module'),
        ),
    ]
