# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 23:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extra_information', '0001_initial'),
        ('contact_information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name | Nombre', max_length=100, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('last_name', models.CharField(db_index=True, help_text='Last name | Apellido paterno', max_length=100, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('mother_last_name', models.CharField(db_index=True, help_text='Mother last name | Apellido materno', max_length=100, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('birthday', models.DateField(help_text='birthday | Fecha nacimiento')),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otros', 'Otros')], help_text='Gender | Género', max_length=9)),
                ('marital_status', models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Separado', 'Separado'), ('Viudo', 'Viudo')], help_text='Marital status | Estado marital o civil', max_length=9)),
                ('photography', models.ImageField(blank=True, default='images/defaults/Default-1.png', help_text='Photography | Fotografía', null=True, upload_to='images/persons/')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('contact_information', models.ManyToManyField(blank=True, help_text='Contact information | Informarción de contacto', to='contact_information.ContactInformation')),
                ('extra_information', models.ManyToManyField(blank=True, help_text='Extra information | Informarción extra', to='extra_information.ExtraInformation')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons - People',
                'db_table': 'person',
                'ordering': ('last_name', 'mother_last_name', 'name'),
            },
        ),
    ]
