# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_person_identification_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contact_information',
            field=models.ManyToManyField(blank=True, help_text='Contact information | Informarción de contacto', null=True, to='contact_information.ContactInformation'),
        ),
        migrations.AlterField(
            model_name='person',
            name='extra_information',
            field=models.ManyToManyField(blank=True, help_text='Extra information | Informarción extra', null=True, to='extra_information.ExtraInformation'),
        ),
    ]
