# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 20:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import url_or_relative_url_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name | Nombre', max_length=100, unique=True)),
                ('url', url_or_relative_url_field.fields.URLOrRelativeURLField(db_index=True, help_text='U.R.L. | U.R.L.', max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Order | Orden', unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('image', models.ImageField(default='images/defaults/Default-1.png', help_text='Image | Imagen', upload_to='images/menus/')),
                ('active', models.BooleanField(default=True, help_text='Active | Activo')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('module', models.ForeignKey(help_text='Module | Módulo', on_delete=django.db.models.deletion.CASCADE, to='modules.Module')),
            ],
            options={
                'verbose_name_plural': 'Menus',
                'db_table': 'menus',
                'verbose_name': 'Menu',
                'ordering': ['order', 'module', 'name', 'url'],
            },
        ),
    ]
