# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import url_or_relative_url_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submenus', '0001_initial'),
        ('menu_submenus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name | Nombre', max_length=100, unique=True)),
                ('url', url_or_relative_url_field.fields.URLOrRelativeURLField(db_index=True, help_text='U.R.L. | U.R.L.', max_length=255, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('sub_menu', models.ManyToManyField(through='menu_submenus.MenuSubMenu', to='submenus.SubMenu')),
            ],
            options={
                'verbose_name_plural': 'Menus',
                'db_table': 'menus',
                'verbose_name': 'Menu',
            },
        ),
    ]
