# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 20:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity_classes', '0001_initial'),
        ('entity_activities', '0001_initial'),
        ('entity_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name | Nombre', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('slogan', models.CharField(blank=True, db_index=True, help_text='Slogan | Slogan', max_length=100, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('initials', models.CharField(blank=True, db_index=True, help_text='Initials | Iniciales', max_length=20, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(20)])),
                ('logo', models.ImageField(blank=True, default=None, help_text='Logo | logo', null=True, upload_to='images/persons/')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('entity_activity', models.ForeignKey(blank=True, help_text='Entity activity | Actividad de la entidad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity_activities.EntityActivity')),
                ('entity_class', models.ForeignKey(blank=True, help_text='Entity class | Clase de la entidad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity_classes.EntityClass')),
                ('entity_type', models.ForeignKey(blank=True, help_text='Entity type | Tipo de la entidad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity_types.EntityType')),
            ],
            options={
                'verbose_name_plural': 'Entities',
                'verbose_name': 'Entity',
                'db_table': 'entities',
                'ordering': ['entity_class', 'entity_type', 'entity_activity', 'name'],
            },
        ),
    ]
