# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='main',
            field=models.BooleanField(default=False, help_text='Main | Principal'),
        ),
    ]
