# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_auto_20180622_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='active',
            field=models.BooleanField(default=True, help_text='Active | Activo'),
        ),
    ]
