# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-23 17:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headquarterses', '0002_auto_20180623_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headquarters',
            name='name',
            field=models.CharField(db_index=True, help_text='Name | Nombre', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
