# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 22:54
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact_information', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('extra_information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name | Nombre', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('last_name', models.CharField(db_index=True, help_text='Last name | Apellido paterno', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('mother_last_name', models.CharField(db_index=True, help_text='Mother last name | Apellido materno', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('birthday', models.DateField(help_text='birthday | Fecha nacimiento')),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otros', 'Otros')], help_text='Gender | Género', max_length=9)),
                ('marital_status', models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Separado', 'Separado'), ('Viudo', 'Viudo')], help_text='Marital status | Estado marital o civil', max_length=9)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Blood group | Grupo sanguíneo', max_length=9, null=True)),
                ('photography', models.ImageField(blank=True, default=None, help_text='Photography | Fotografía', null=True, upload_to='image/persons/')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('active', models.BooleanField(default=True, help_text='Active | Activo')),
                ('auth_user', models.OneToOneField(help_text='Auth user | Usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contact_information', models.ManyToManyField(blank=True, help_text='Contact information | Informarción de contacto', to='contact_information.ContactInformation')),
                ('extra_information', models.ForeignKey(blank=True, help_text='Extra information | Informarción extra', null=True, on_delete=django.db.models.deletion.SET_NULL, to='extra_information.ExtraInformation')),
            ],
            options={
                'verbose_name': 'Auth User Profile',
                'verbose_name_plural': 'Auth User Profiles',
                'db_table': 'auth_user_profiles',
            },
        ),
    ]
