# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuserprofile',
            name='photography',
            field=models.ImageField(blank=True, default=None, help_text='Photography | Fotografía', null=True, upload_to='images/persons/'),
        ),
    ]
