# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 15:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_profiles', '0002_auto_20180611_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuserprofile',
            name='last_name',
            field=models.CharField(db_index=True, help_text='Last name | Apellido paterno', max_length=100, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='authuserprofile',
            name='mother_last_name',
            field=models.CharField(db_index=True, help_text='Mother last name | Apellido materno', max_length=100, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='authuserprofile',
            name='name',
            field=models.CharField(db_index=True, help_text='Name | Nombre', max_length=100, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
