# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_profiles', '0003_auto_20180620_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuserprofile',
            name='photography',
            field=models.ImageField(blank=True, default='images/defaults/Default-1.png', help_text='Photography | Fotografía', null=True, upload_to='images/persons/'),
        ),
    ]
