# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-22 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_information', '0001_initial'),
        ('auth_user_profiles', '0004_auto_20180622_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuserprofile',
            name='extra_information',
        ),
        migrations.AddField(
            model_name='authuserprofile',
            name='extra_information',
            field=models.ManyToManyField(blank=True, help_text='Extra information | Informarción extra', to='extra_information.ExtraInformation'),
        ),
    ]
